spring:
  application:
    name: "test"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.28.161.241:33060/demo?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&createDatabaseIfNotExist=true
    username: root
    password: my-secret-pw
mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:/mybatis/*.xml
logging:
  file:
    name: log/log.log
  level:
    root: info
    hugo: debug
